### PR TITLE
fix: default base fee state in genesis

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #918
Solution:
- initialise the default base fee value in genesis

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by fedekunze — APPROVED** [review]
ACK, can you add a changelog entry?

**Comment by yihuang** [comment]
I first thought this solve the failing test case in https://github.com/tharsis/ethermint/pull/916, but in the end, I found it's not.
So do you want to still merge this one? I think it doesn't make much difference.

**Comment by fedekunze** [comment]
I think it's a good addition. I'll reopen it

**Comment by yihuang** [comment]
> I think it's a good addition. I'll reopen it

great, changelog added.

**Pull request merged**
