### PR TITLE
Add opcode test to suites

### PR DESCRIPTION
**Pull request by yijiasu-crypto**
Closes: #XXX

## Description

Add some opcode test from the original `go-ethereum` protocol. Original test files can be found here: https://github.com/ethereum/go-ethereum/tree/master/tests/solidity

The opcode test will ask EVM to run all opcode defined by Ethereum Yellow Paper to make sure the EVM performs correctly.

Run `yarn test --network ethermint opcode` to perform this test.

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by fedekunze — COMMENTED** [review]
this looks good but I'm afraid the contracts on geth were updated for the last time 2 years ago so there might be a few opcodes missing. Can you check that and add them too if possible? 

Also, if you could add a README.md on the `opcode/` directory to run the tests that would be amazing

**Comment by yijiasu-crypto** [comment]
> this looks good but I'm afraid the contracts on geth were updated for the last time 2 years ago so there might be a few opcodes missing. Can you check that and add them too if possible?
> 
> Also, if you could add a README.md on the `opcode/` directory to run the tests that would be amazing

Sure. Will do

**Comment by fedekunze** [comment]
@yijiasu-crypto are you going to add the opcodes? or should we add them on a separate PR?

**Comment by yijiasu-crypto** [comment]
Yes I think we could just merge this.

I will issue a separate PR to add more opcode tests.

**Review by fedekunze — APPROVED** [review]

**Comment by fedekunze** [comment]
> I will issue a separate PR to add more opcode tests.

@yijiasu-crypto can you create an issue to keep track of progress?

**Pull request merged**
