### PR TITLE
Miner docs

### PR DESCRIPTION
**Pull request by hanchon**
Closes: #477

## Description

Miner RPC docs updated.
This PR also includes a fix to use the `current configuration` instead of the `default` when reading the configuration, to avoid overwriting the user configuration when saving the new gas price to disk.
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by hanchon** [comment]
Should I also update the Changelog file with this fix?  More info on the issue #477

**Review by fedekunze — APPROVED** [review]
ACK thanks!

**Comment by fedekunze** [comment]
> Should I also update the Changelog file with this fix? More info on the issue #477

@hanchon yes, if possible

**Comment by hanchon** [comment]
> > Should I also update the Changelog file with this fix? More info on the issue #477
> 
> @hanchon yes, if possible

Fix added to the Changelog

**Pull request merged**
