### PR TITLE
Problem: etherjs smartcontract cannot change state (fix #257)

### LINKED ISSUE #257: Problem: etherjs smartcontract cannot change state
cannot change the state of the smart contract
src: 
https://github.com/leejw51crypto/ethermint.git
branch: etherjs
folder: mytest/mytest

### env variable for testing
MYMNEMONICS  <- your mnemonics

```
1. git clone https://github.com/leejw51crypto/ethermint.git
2. cd ethermint
3. git checkout etherjs
4. cd mytest/mytest
5. make
```

## when run with ganache
```
BigNumber { _hex: '0x00', _isBigNumber: true }
{
  nonce: 17,
  gasPrice: BigNumber { _hex: '0x04a817c800', _isBigNumber: true },
  gasLimit: BigNumber { _hex: '0xa2ae', _isBigNumber: true },
  to: '0x2831Fb598Fb659EC881585557C3e36414BfC32e5',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  data: '0x6057361d0000000000000000000000000000000000000000000000000000000000000015',
  chainId: 1337,
  v: 2709,
  r: '0x14ecfc5d6e69a89278ab8e2a4334898f25e2677cc38e0bd509791b5a07bdffaf',
  s: '0x6fca8a9e61a78efe115f9983b3f1b89a79e1eca0331dd84f52a3a06d9da210fc',
  from: '0x48b212A71eBbB202F7cfD1aACee3A36FdE2Fbc51',
  hash: '0xe0e6d9b1f4802245fa8a652bcdbe02c8dbf300d15491b590ff1c8c105d10617e',
  type: null,
  wait: [Function (anonymous)]
}
BigNumber { _hex: '0x15', _isBigNumber: true }
```

## when run with ethermint
```
BigNumber { _hex: '0x00', _isBigNumber: true }
{
  nonce: 6,
  gasPrice: BigNumber { _hex: '0x14', _isBigNumber: true },
  gasLimit: BigNumber { _hex: '0x52d4', _isBigNumber: true },
  to: '0x5589184cE12715763c409b0e33ad6f8f075d0377',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  data: '0x6057361d0000000000000000000000000000000000000000000000000000000000000015',
  chainId: 2,
  v: 39,
  r: '0x35db8a1ca2054e49c1d913ac3566f654a2c47072b71592926141af57afb93fed',
  s: '0x0ff0108bc624f304d329d78e6bb43c7da1ff60f436ae3626b47b7c33a24de54d',
  from: '0x48b212A71eBbB202F7cfD1aACee3A36FdE2Fbc51',
  hash: '0xac7a4efd5df15dd6b798b4f58bdc7f66e3e54eaf17f624e0525c539de57b14db',
  type: null,
  wait: [Function (anonymous)]
}
BigNumber { _hex: '0x00', _isBigNumber: true }
```

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: increase base gas to make similar with ethereum

### CODE REVIEW

**Comment by thomas-nguy** [comment]
I have tried current main and its consistent with infura (no contract call)

I think its better to fix the calculation rather than add a fixed value.

```
➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe", "data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}],"id":1}'  -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x52d4"}
➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe", "data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}],"id":1}'  -H "Content-Type: application/json" https://ropsten.infura.io/v3/<project_id>
{"jsonrpc":"2.0","id":1,"result":"0x52d4"}%

```

```

➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "value":"0x16345785d8a00000"}],"id":1}'  -H "Content-Type: application/json" https://ropsten.infura.io/v3/<projectId>
{"jsonrpc":"2.0","id":1,"result":"0x5208"}%
➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "value":"0x16345785d8a00000"}],"id":1}'  -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x5208"}

```

**Comment by leejw51crypto** [comment]
ok , i'll find a way to compute

**Comment by thomas-nguy** [comment]
check this method
https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L262

(it refund max half consumed, maybe the logic is different with geth)

**Comment by yijiasu** [comment]
> I have tried current main and its consistent with infura (no contract call)
> 
> I think its better to fix the calculation rather than add a fixed value.
> 
> ```
> ➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe", "data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}],"id":1}'  -H "Content-Type: application/json" http://localhost:8545
> {"jsonrpc":"2.0","id":1,"result":"0x52d4"}
> ➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe", "data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}],"id":1}'  -H "Content-Type: application/json" https://ropsten.infura.io/v3/<project_id>
> {"jsonrpc":"2.0","id":1,"result":"0x52d4"}%
> ```
> 
> ```
> 
> ➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "value":"0x16345785d8a00000"}],"id":1}'  -H "Content-Type: application/json" https://ropsten.infura.io/v3/<projectId>
> {"jsonrpc":"2.0","id":1,"result":"0x5208"}%
> ➜  ethermint git:(thomas/gas_estimate) ✗ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "to":"0x7cB61D4117AE31a12E393a1Cfa3BaC666481D02E", "value":"0x16345785d8a00000"}],"id":1}'  -H "Content-Type: application/json" http://localhost:8545
> {"jsonrpc":"2.0","id":1,"result":"0x5208"}
> ```

If the calculation is equal to the value from infura, then there's no issue at all. It's expected to have the same gas value from any existing Etherum network

what's going wrong here?

**Comment by leejw51crypto** [comment]
21204 is not enough,  it should 41646,
i tried 41645, not working

Ganache: 0xa2ae = 41646
Tharsis: 0x52d4 = 21204

**Comment by yihuang** [comment]
> 21204 is not enough, it should be equal or above than 41646,
> i tried 41645, not working
> 
> Ganache: 0xa2ae = 41646
> Tharsis: 0x52d4 = 21204

Probably this issue: https://github.com/tharsis/ethermint/issues/268

**Comment by thomas-nguy** [comment]
```
Is 0x52d4 (dec. 21204) enough for executing the call? What's the value in its compiled ABI?
```

I used the example from the rpc doc. Maybe its just a memo.

@leejw51crypto what is your code to return `0xa2ae = 41646` ?

**Comment by leejw51crypto** [comment]
return hexutil.Uint64(data.GasUsed + 40000), nil
	
i added 40000

**Comment by leejw51crypto** [comment]
i'll rebase asfter
#268 is resolved

**Comment by leejw51crypto** [comment]
closed by 
https://github.com/tharsis/ethermint/pull/272

**Pull request closed without merging**
