### PR TITLE
[ENG-4] startport: setup

### PR DESCRIPTION
**Pull request by fedekunze**
## Description

You can now run the network using [starport](https://docs.starport.network/intro/install):

`starport serve`

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by fadeev** [comment]
Can we also perhaps merge this into `cosmos/ethermint`?

**Comment by fedekunze** [comment]
> Can we also perhaps merge this into cosmos/ethermint?

@fadeev the cosmos repo is not up to date yet with the latest stargate and geth and state changes

**Comment by khoslaventures** [comment]
We should probably add some installation instructions for starport?

**Review by khoslaventures — APPROVED** [review]

**Comment by fedekunze** [comment]
> We should probably add some installation instructions for starport?

yes, we need to update the documentation. Will do it on a follow up

**Comment by fadeev** [comment]
fwiw we're releasing Starport v0.16 on Monday and it has `protoc` bundled and Go paths are automatically handled, so the only the user needs to do is:

```
curl https://get.starport.network/starport! | bash
```

(no dependencies, except Go)

**Pull request merged**
