### PR TITLE
Problem: too many files open (fix #768)

### LINKED ISSUE #768: Problem: uses too many files open
on ubuntu , default 1024 open file count is not enough.
add some explicit resource management in rpc handlers

### PR DESCRIPTION
**Pull request by leejw51crypto**
Cause: golang http.Server is very fast and high performance, so if rpc usage is very hight, it affects p2p and consens
because they're in the same process. shares open files limit.

Solution: not use keep-alive, 0 timeout, sleep 5 milli-seconds for new connection
total open files is about 60 (previously over 1024 open files)

gives more priority to p2p and consensus
and make core more stable and p2p faster

ulimit -n (open file count for the process), varies with the system
mac: 256
linux: 1024

### CODE REVIEW

**Comment by JayT106** [comment]
should we use `rate.limit` instead of sleep? Also, the file open limit can be setup before running the node, I think we might suggest to the user what's the proper number when running for the production in documents?

**Comment by leejw51crypto** [comment]
i'll add rate control for sleeping time, and will add to the document

**Comment by leejw51crypto** [comment]
add to the document,
because time.sleep can affect rpc performance, removed

**Comment by odeke-em** [comment]
@leejw51crypto thank you for this change! I have been investigating this and the problem here is that too many files get opened and closed too fast and this can exhaust the system, which is why you see that 5+ seconds of wait reduces the exhaustion. Please see

I am working on reducing the number of files that Tendermint opens starting https://gist.github.com/odeke-em/a7807f08ef29dc4957e2f92b1f52d38e which if you edit your Tendermint module in $GOPATH/pkg/mod, you'll see some relief here. The remedies that I am working on involve using a single file then doing file.Seek to the start then writing and invoking .Sync, then for other changes I shall explore using mmap as well. I'd say let's not reduce transactions per second by using a 5 second sleep that won't solve the problem if the number of connections is multiplied. Thank you.

**Comment by tomtau** [comment]
closing this as the root cause is to be fixed in Tendermint by @odeke-em

**Pull request closed without merging**
