### PR TITLE
Problem: EVM keeper keeps intermediate states inside

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #664

## Description

- Migrate the `StateDB` methods to keeper style, aka. passing `sdk.Context` explicitly, returns `error` when needed. see [StateDBKeeper](https://github.com/tharsis/ethermint/pull/663/files#diff-0216dbb8dcfac11bf9947259e7f6638eeb718e178f76c5148bf165b1439a6366R67)
- Create another [StateDB struct](https://github.com/tharsis/ethermint/pull/663/files#diff-41507b908666b6b9b7906968a5178c9231ede5324f00c2d6514016ae7c0e4e40R16) to handle `ctxStack` and `stateErr` and implements `Snapshot`/`RevertSnapshot`/`GetCommittedState`, delegate all the other `StateDB` methods to the keeper.
- `ApplyMessage` create `StateDB` struct on the fly, either commit or discard it before return.

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by yihuang** [comment]
> hold it for now, since there are another refactoring PR ongoing, after that one fixed, this one will become cleaner.

rebased, it's much cleaner now.

**Comment by fedekunze** [comment]
@yihuang sorry about the delay, I'll look into this in-depth during the next couple of days

**Comment by yihuang** [comment]
> @yihuang sorry about the delay, I'll look into this in-depth during the next couple of days

Can you have a look at this issue: https://github.com/tharsis/ethermint/issues/710. Deep context stack is still slow, to fix that, we might need more refactoring, journal logs?

**Comment by yihuang** [comment]
I think it's better to review together here: https://github.com/tharsis/ethermint/pull/729

**Pull request closed without merging**
