### PR TITLE
reproducible integration test environment

### LINKED ISSUE #280: reproducible integration test environment with ethermint and geth
__Proposal:__ local integration test environment with both ethermint and geth

__Current behavior:__ only ethermint start script

__Desired behavior:__
- scripts that start ethermint and geth local devnet with same genesis parameters and fund allocations.
- the environment is easily reproducible

__Use case:__ to easily run integration tests against both ethermint and geth

port from https://github.com/yihuang/web3-integration-tests

### PR DESCRIPTION
**Pull request by yihuang**
Closes #280

## Description

[README.md](https://github.com/tharsis/ethermint/blob/ecd51ac301a3b0cd6f1654a638b2b6c7b5f01121/tests/README.md)

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by fedekunze — APPROVED** [review]
LGTM. Can you move all these files to a new `tests/nix` folder? Also maybe add a README.md for instructions on how to run these. 

Follow-up PR, add CI test on github workflows

**Comment by yihuang** [comment]
> LGTM. Can you move all these files to a new `tests/nix` folder? Also maybe add a README.md for instructions on how to run these.
> 
> Follow-up PR, add CI test on github workflows

done

**Comment by yihuang** [comment]
Maybe this is less important since in truffle, we can also test against both ethermint and ganache, we probably just need to improve integration tests scripts to run the tests against both.

**Comment by fedekunze** [comment]
no clue why the test is failing. This PR doesn't seem to update any relevant code

**Comment by yihuang** [comment]
> no clue why the test is failing. This PR doesn't seem to update any relevant code

Let's close this one for now? we can reopen it when it's actually needed.

**Pull request closed without merging**
