### PR TITLE
Problem: import/export genesis roundtrip test fails for contract storage

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #589

- don't hash the key again in InitGenesis

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by yihuang** [comment]
Alternatively, can we just remove the hash in SetState?

**Comment by yihuang** [comment]
> Alternatively, can we just remove the hash in SetState?

I just removed the hash completely in newer commit.

**Comment by yihuang** [comment]
Verified in cronos's integration test: https://github.com/crypto-org-chain/cronos/pull/104/files#diff-4bc634280ffa32d380c3cca748c078f199cf11056710fa67713f672133ebfc86R34

the key is not hashed now.

**Review by fedekunze — APPROVED** [review]
Thanks @yihuang. Can you add a state machine breaking item on the changelog?

**Comment by yihuang** [comment]
> Thanks @yihuang. Can you add a state machine breaking item on the changelog?

done

**Review by fedekunze — APPROVED** [review]

**Comment by yihuang** [comment]
it seems the gas estimate issue is fixed too.

**Pull request merged**
