### PR TITLE
Problem: fix eth log override #343

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: override with callback function

### CODE REVIEW

**Comment by leejw51crypto** [comment]
evm logs are printed only with debug option,
if it is printed in production, printing logs itself will dramatically slow down the performance.

image

**Comment by leejw51crypto** [comment]
image

**Comment by fedekunze** [comment]
thanks @leejw51crypto, can you fix the conflicts?

**Comment by leejw51crypto** [comment]
ok, i'll check it

**Comment by leejw51crypto** [comment]
rebase done

**Pull request merged**
